# This yaml file is creating a note port for the platformservice
# This can be run with the command "kubectl apply -f platforms-np-srv.yaml"

apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector: # is selecting which
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80 # Node Port is the port on the inside of the node port
      targetPort: 80 # Target Port is the port of the service
